export const typography = {
  fontFamily: {
    regular: 'Fredoka-Regular',
    light: 'Fredoka-Light',
    medium: 'Fredoka-Medium',
    semiBold: 'Fredoka-SemiBold',
    bold: 'Fredoka-Bold',
  },
  fontSize: {
    xs: 12,
    sm: 14,
    base: 16,
    lg: 18,
    xl: 20,
    '2xl': 24,
    '3xl': 30,
    '4xl': 36,
  },
  lineHeight: {
    none: 1,
    tight: 1.25,
    snug: 1.375,
    normal: 1.5,
    relaxed: 1.625,
    loose: 2,
    xs: 16,
    sm: 20,
    base: 24,
    lg: 28,
    xl: 32,
    '2xl': 40,
    '3xl': 48,
  },
  letterSpacing: {
    tighter: -0.8,
    tight: -0.4,
    normal: 0,
    wide: 0.4,
    wider: 0.8,
  },
  body: {
    fontSize: 16,
    fontWeight: '400' as const,
  },
  heading1: {
    fontSize: 28,
    fontWeight: 'bold' as const,
  },
  heading2: {
    fontSize: 22,
    fontWeight: 'bold' as const,
  },
  heading3: {
    fontSize: 18,
    fontWeight: 'bold' as const,
  },
  button: {
    fontSize: 16,
    fontWeight: '600' as const,
    textTransform: 'uppercase' as const,
  },
};

export const textStyles = {
  heading1: {
    fontFamily: typography.fontFamily.bold,
    fontSize: typography.fontSize['4xl'],
    lineHeight: typography.lineHeight['3xl'],
    letterSpacing: typography.letterSpacing.tight,
    includeFontPadding: false,
    textAlignVertical: 'center' as const,
  },
  heading2: {
    fontFamily: typography.fontFamily.semiBold,
    fontSize: typography.fontSize['3xl'],
    lineHeight: typography.lineHeight['2xl'],
    letterSpacing: typography.letterSpacing.tight,
    includeFontPadding: false,
    textAlignVertical: 'center' as const,
  },
  heading3: {
    fontFamily: typography.fontFamily.medium,
    fontSize: typography.fontSize['2xl'],
    lineHeight: typography.lineHeight.xl,
    letterSpacing: typography.letterSpacing.tight,
    includeFontPadding: false,
    textAlignVertical: 'center' as const,
  },
  body: {
    fontFamily: typography.fontFamily.regular,
    fontSize: typography.fontSize.base,
    lineHeight: typography.lineHeight.base,
    letterSpacing: typography.letterSpacing.normal,
    includeFontPadding: false,
    textAlignVertical: 'center' as const,
  },
  button: {
    fontFamily: typography.fontFamily.medium,
    fontSize: typography.fontSize.base,
    lineHeight: typography.lineHeight.base,
    letterSpacing: typography.letterSpacing.wide,
    includeFontPadding: false,
    textAlignVertical: 'center' as const,
  },
  bodyLarge: {
    fontFamily: typography.fontFamily.regular,
    fontSize: typography.fontSize.lg,
    lineHeight: typography.lineHeight.lg,
    letterSpacing: typography.letterSpacing.normal,
    includeFontPadding: false,
    textAlignVertical: 'center' as const,
  },
  caption: {
    fontFamily: typography.fontFamily.light,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.lineHeight.sm,
    letterSpacing: typography.letterSpacing.normal,
    includeFontPadding: false,
    textAlignVertical: 'center' as const,
  },
  label: {
    fontFamily: typography.fontFamily.medium,
    fontSize: typography.fontSize.sm,
    lineHeight: typography.lineHeight.sm,
    letterSpacing: typography.letterSpacing.normal,
    includeFontPadding: false,
    textAlignVertical: 'center' as const,
  },
};
