// Enhanced tracing segments for all letters (A-Z) and numbers (0-9)
// Each segment now includes stroke order, type, difficulty, and hints

export interface EnhancedSegment {
  path: string;
  pointer: [number, number];
  direction: "left" | "right" | "up" | "down";
  strokeOrder: number;
  strokeType: "main" | "secondary" | "crossbar" | "curve" | "diagonal";
  difficulty: "easy" | "medium" | "hard";
  audioHint?: string;
  visualHint?: string;
}

export const tracingSegments: Record<string, EnhancedSegment[]> = {
  // Letters with enhanced information
  A: [
    {
      path: "M200,80 L150,320",
      pointer: [200, 80],
      direction: "down",
      strokeOrder: 1,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_one_left",
      visualHint: "Start at the top, draw down to the left",
    },
    {
      path: "M200,80 L250,320",
      pointer: [200, 80],
      direction: "down",
      strokeOrder: 2,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_two_right",
      visualHint: "From the top, draw down to the right",
    },
    {
      path: "M170,220 L230,220",
      pointer: [170, 220],
      direction: "right",
      strokeOrder: 3,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_three_cross",
      visualHint: "Add a line across the middle",
    },
  ],
  B: [
    {
      path: "M150,80 L150,320",
      pointer: [150, 80],
      direction: "down",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_down",
      visualHint: "Draw a straight line down",
    },
    {
      path: "M150,80 Q230,120 150,200",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 2,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_two_curve",
      visualHint: "Add a curve at the top",
    },
    {
      path: "M150,200 Q230,240 150,320",
      pointer: [150, 200],
      direction: "right",
      strokeOrder: 3,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_three_curve",
      visualHint: "Add a curve at the bottom",
    },
  ],
  C: [
    {
      path: "M250,120 Q200,80 150,120 Q150,200 200,200 Q250,200 250,280 Q200,320 150,280",
      pointer: [250, 120],
      direction: "left",
      strokeOrder: 1,
      strokeType: "curve",
      difficulty: "hard",
      audioHint: "stroke_one_curve",
      visualHint: "Draw a big curve from top to bottom",
    },
  ],
  D: [
    {
      path: "M150,80 L150,320",
      pointer: [150, 80],
      direction: "down",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_down",
      visualHint: "Draw a straight line down",
    },
    {
      path: "M150,80 Q230,120 150,200 Q230,240 150,320",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 2,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_two_curve",
      visualHint: "Add a big curve to connect the line",
    },
  ],
  E: [
    {
      path: "M150,80 L150,320",
      pointer: [150, 80],
      direction: "down",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_down",
      visualHint: "Draw a straight line down",
    },
    {
      path: "M150,80 L250,80",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 2,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_two_top",
      visualHint: "Add a line across the top",
    },
    {
      path: "M150,200 L230,200",
      pointer: [150, 200],
      direction: "right",
      strokeOrder: 3,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_three_middle",
      visualHint: "Add a line across the middle",
    },
    {
      path: "M150,320 L250,320",
      pointer: [150, 320],
      direction: "right",
      strokeOrder: 4,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_four_bottom",
      visualHint: "Add a line across the bottom",
    },
  ],
  F: [
    {
      path: "M150,80 L150,320",
      pointer: [150, 80],
      direction: "down",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_down",
      visualHint: "Draw a straight line down",
    },
    {
      path: "M150,80 L250,80",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 2,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_two_top",
      visualHint: "Add a line across the top",
    },
    {
      path: "M150,200 L230,200",
      pointer: [150, 200],
      direction: "right",
      strokeOrder: 3,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_three_middle",
      visualHint: "Add a line across the middle",
    },
  ],
  G: [
    {
      path: "M250,120 Q200,80 150,120 Q150,200 200,200 Q250,200 250,280 Q200,320 150,280",
      pointer: [250, 120],
      direction: "left",
      strokeOrder: 1,
      strokeType: "curve",
      difficulty: "hard",
      audioHint: "stroke_one_curve",
      visualHint: "Draw a big curve from top to bottom",
    },
    {
      path: "M200,200 L250,200",
      pointer: [200, 200],
      direction: "right",
      strokeOrder: 2,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_two_cross",
      visualHint: "Add a line across the middle",
    },
  ],
  H: [
    {
      path: "M150,80 L150,320",
      pointer: [150, 80],
      direction: "down",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_left",
      visualHint: "Draw a straight line down on the left",
    },
    {
      path: "M250,80 L250,320",
      pointer: [250, 80],
      direction: "down",
      strokeOrder: 2,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_two_right",
      visualHint: "Draw a straight line down on the right",
    },
    {
      path: "M150,200 L250,200",
      pointer: [150, 200],
      direction: "right",
      strokeOrder: 3,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_three_cross",
      visualHint: "Connect the lines with a line across the middle",
    },
  ],
  I: [
    {
      path: "M200,80 L200,320",
      pointer: [200, 80],
      direction: "down",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_down",
      visualHint: "Draw a straight line down in the middle",
    },
    {
      path: "M180,80 L220,80",
      pointer: [180, 80],
      direction: "right",
      strokeOrder: 2,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_two_top",
      visualHint: "Add a line across the top",
    },
    {
      path: "M180,320 L220,320",
      pointer: [180, 320],
      direction: "right",
      strokeOrder: 3,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_three_bottom",
      visualHint: "Add a line across the bottom",
    },
  ],
  J: [
    {
      path: "M250,80 L250,280",
      pointer: [250, 80],
      direction: "down",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_down",
      visualHint: "Draw a straight line down",
    },
    {
      path: "M250,280 Q200,280 180,300",
      pointer: [250, 280],
      direction: "left",
      strokeOrder: 2,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_two_curve",
      visualHint: "Add a curve at the bottom",
    },
  ],
  K: [
    {
      path: "M150,80 L150,320",
      pointer: [150, 80],
      direction: "down",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_down",
      visualHint: "Draw a straight line down",
    },
    {
      path: "M150,200 L250,120",
      pointer: [150, 200],
      direction: "right",
      strokeOrder: 2,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_two_up",
      visualHint: "Add a line going up to the right",
    },
    {
      path: "M150,200 L250,280",
      pointer: [150, 200],
      direction: "right",
      strokeOrder: 3,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_three_down",
      visualHint: "Add a line going down to the right",
    },
  ],
  L: [
    {
      path: "M150,80 L150,320",
      pointer: [150, 80],
      direction: "down",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_down",
      visualHint: "Draw a straight line down",
    },
    {
      path: "M150,320 L250,320",
      pointer: [150, 320],
      direction: "right",
      strokeOrder: 2,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_two_bottom",
      visualHint: "Add a line across the bottom",
    },
  ],
  M: [
    {
      path: "M150,320 L150,80",
      pointer: [150, 320],
      direction: "up",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_up",
      visualHint: "Draw a straight line up on the left",
    },
    {
      path: "M150,80 L200,200",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 2,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_two_down",
      visualHint: "Add a line going down to the middle",
    },
    {
      path: "M200,200 L250,80",
      pointer: [200, 200],
      direction: "right",
      strokeOrder: 3,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_three_up",
      visualHint: "Add a line going up to the right",
    },
    {
      path: "M250,80 L250,320",
      pointer: [250, 80],
      direction: "down",
      strokeOrder: 4,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_four_down",
      visualHint: "Draw a straight line down on the right",
    },
  ],
  N: [
    {
      path: "M150,320 L150,80",
      pointer: [150, 320],
      direction: "up",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_up",
      visualHint: "Draw a straight line up on the left",
    },
    {
      path: "M150,80 L250,320",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 2,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_two_down",
      visualHint: "Add a line going down to the right",
    },
    {
      path: "M250,320 L250,80",
      pointer: [250, 320],
      direction: "up",
      strokeOrder: 3,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_three_up",
      visualHint: "Draw a straight line up on the right",
    },
  ],
  O: [
    {
      path: "M200,80 Q150,80 150,200 Q150,320 200,320 Q250,320 250,200 Q250,80 200,80",
      pointer: [200, 80],
      direction: "left",
      strokeOrder: 1,
      strokeType: "curve",
      difficulty: "hard",
      audioHint: "stroke_one_circle",
      visualHint: "Draw a big circle",
    },
  ],
  P: [
    {
      path: "M150,320 L150,80",
      pointer: [150, 320],
      direction: "up",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_up",
      visualHint: "Draw a straight line up",
    },
    {
      path: "M150,80 Q200,80 200,140 Q200,200 150,200",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 2,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_two_curve",
      visualHint: "Add a curve at the top",
    },
  ],
  Q: [
    {
      path: "M200,80 Q150,80 150,200 Q150,320 200,320 Q250,320 250,200 Q250,80 200,80",
      pointer: [200, 80],
      direction: "left",
      strokeOrder: 1,
      strokeType: "curve",
      difficulty: "hard",
      audioHint: "stroke_one_circle",
      visualHint: "Draw a big circle",
    },
    {
      path: "M200,200 L250,320",
      pointer: [200, 200],
      direction: "right",
      strokeOrder: 2,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_two_tail",
      visualHint: "Add a tail going down to the right",
    },
  ],
  R: [
    {
      path: "M150,320 L150,80",
      pointer: [150, 320],
      direction: "up",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_up",
      visualHint: "Draw a straight line up",
    },
    {
      path: "M150,80 Q200,80 200,140 Q200,200 150,200",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 2,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_two_curve",
      visualHint: "Add a curve at the top",
    },
    {
      path: "M150,200 L250,320",
      pointer: [150, 200],
      direction: "right",
      strokeOrder: 3,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_three_tail",
      visualHint: "Add a tail going down to the right",
    },
  ],
  S: [
    {
      path: "M250,120 Q200,80 150,120 Q150,200 250,200 Q200,240 150,280 Q200,320 250,280",
      pointer: [250, 120],
      direction: "left",
      strokeOrder: 1,
      strokeType: "curve",
      difficulty: "hard",
      audioHint: "stroke_one_snake",
      visualHint: "Draw a snake-like curve",
    },
  ],
  T: [
    {
      path: "M200,80 L200,320",
      pointer: [200, 80],
      direction: "down",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_down",
      visualHint: "Draw a straight line down in the middle",
    },
    {
      path: "M150,80 L250,80",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 2,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_two_top",
      visualHint: "Add a line across the top",
    },
  ],
  U: [
    {
      path: "M150,80 L150,280",
      pointer: [150, 80],
      direction: "down",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_down",
      visualHint: "Draw a straight line down on the left",
    },
    {
      path: "M150,280 Q150,320 200,320 Q250,320 250,280",
      pointer: [150, 280],
      direction: "right",
      strokeOrder: 2,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_two_curve",
      visualHint: "Add a curve at the bottom",
    },
    {
      path: "M250,280 L250,80",
      pointer: [250, 280],
      direction: "up",
      strokeOrder: 3,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_three_up",
      visualHint: "Draw a straight line up on the right",
    },
  ],
  V: [
    {
      path: "M150,80 L200,320",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 1,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_one_down",
      visualHint: "Draw a line going down to the right",
    },
    {
      path: "M200,320 L250,80",
      pointer: [200, 320],
      direction: "right",
      strokeOrder: 2,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_two_up",
      visualHint: "Add a line going up to the right",
    },
  ],
  W: [
    {
      path: "M150,80 L180,320",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 1,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_one_down",
      visualHint: "Draw a line going down to the right",
    },
    {
      path: "M180,320 L200,200",
      pointer: [180, 320],
      direction: "right",
      strokeOrder: 2,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_two_up",
      visualHint: "Add a line going up to the right",
    },
    {
      path: "M200,200 L220,320",
      pointer: [200, 200],
      direction: "right",
      strokeOrder: 3,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_three_down",
      visualHint: "Add a line going down to the right",
    },
    {
      path: "M220,320 L250,80",
      pointer: [220, 320],
      direction: "right",
      strokeOrder: 4,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_four_up",
      visualHint: "Add a line going up to the right",
    },
  ],
  X: [
    {
      path: "M150,80 L250,320",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 1,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_one_down",
      visualHint: "Draw a line going down to the right",
    },
    {
      path: "M250,80 L150,320",
      pointer: [250, 80],
      direction: "left",
      strokeOrder: 2,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_two_down",
      visualHint: "Add a line going down to the left",
    },
  ],
  Y: [
    {
      path: "M150,80 L200,200",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 1,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_one_down",
      visualHint: "Draw a line going down to the right",
    },
    {
      path: "M250,80 L200,200",
      pointer: [250, 80],
      direction: "left",
      strokeOrder: 2,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_two_down",
      visualHint: "Add a line going down to the left",
    },
    {
      path: "M200,200 L200,320",
      pointer: [200, 200],
      direction: "down",
      strokeOrder: 3,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_three_down",
      visualHint: "Draw a straight line down from the middle",
    },
  ],
  Z: [
    {
      path: "M150,80 L250,80",
      pointer: [150, 80],
      direction: "right",
      strokeOrder: 1,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_one_top",
      visualHint: "Draw a line across the top",
    },
    {
      path: "M250,80 L150,320",
      pointer: [250, 80],
      direction: "left",
      strokeOrder: 2,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_two_down",
      visualHint: "Add a line going down to the left",
    },
    {
      path: "M150,320 L250,320",
      pointer: [150, 320],
      direction: "right",
      strokeOrder: 3,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_three_bottom",
      visualHint: "Add a line across the bottom",
    },
  ],

  // Numbers with enhanced information
  "0": [
    {
      path: "M200,80 Q150,80 150,200 Q150,320 200,320 Q250,320 250,200 Q250,80 200,80",
      pointer: [200, 80],
      direction: "left",
      strokeOrder: 1,
      strokeType: "curve",
      difficulty: "hard",
      audioHint: "stroke_one_circle",
      visualHint: "Draw a big circle",
    },
  ],
  "1": [
    {
      path: "M200,100 L200,320",
      pointer: [200, 100],
      direction: "down",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_down",
      visualHint: "Draw a straight line down",
    },
  ],
  "2": [
    {
      path: "M150,150 Q200,80 250,150",
      pointer: [150, 150],
      direction: "right",
      strokeOrder: 1,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_one_curve",
      visualHint: "Draw a curve at the top",
    },
    {
      path: "M250,150 Q250,250 150,320",
      pointer: [250, 150],
      direction: "down",
      strokeOrder: 2,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_two_curve",
      visualHint: "Add a curve going down to the left",
    },
    {
      path: "M150,320 L250,320",
      pointer: [150, 320],
      direction: "right",
      strokeOrder: 3,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_three_bottom",
      visualHint: "Add a line across the bottom",
    },
  ],
  "3": [
    {
      path: "M150,250 Q200,200 250,250",
      pointer: [150, 250],
      direction: "right",
      strokeOrder: 1,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_one_top",
      visualHint: "Draw a curve at the top",
    },
    {
      path: "M250,250 Q200,300 250,350",
      pointer: [250, 250],
      direction: "down",
      strokeOrder: 2,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_two_middle",
      visualHint: "Add a curve in the middle",
    },
    {
      path: "M250,350 Q200,400 150,350",
      pointer: [250, 350],
      direction: "left",
      strokeOrder: 3,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_three_bottom",
      visualHint: "Add a curve at the bottom",
    },
  ],
  "4": [
    {
      path: "M250,350 V200",
      pointer: [250, 350],
      direction: "up",
      strokeOrder: 1,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_one_up",
      visualHint: "Draw a straight line up on the right",
    },
    {
      path: "M150,350 L250,350",
      pointer: [150, 350],
      direction: "right",
      strokeOrder: 2,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_two_across",
      visualHint: "Add a line across the bottom",
    },
    {
      path: "M150,350 L150,200",
      pointer: [150, 350],
      direction: "up",
      strokeOrder: 3,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_three_up",
      visualHint: "Draw a straight line up on the left",
    },
  ],
  "5": [
    {
      path: "M250,200 H150",
      pointer: [250, 200],
      direction: "left",
      strokeOrder: 1,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_one_across",
      visualHint: "Draw a line across the top",
    },
    {
      path: "M150,200 V300",
      pointer: [150, 200],
      direction: "down",
      strokeOrder: 2,
      strokeType: "main",
      difficulty: "easy",
      audioHint: "stroke_two_down",
      visualHint: "Draw a straight line down",
    },
    {
      path: "M150,300 Q200,300 250,350",
      pointer: [150, 300],
      direction: "right",
      strokeOrder: 3,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_three_curve",
      visualHint: "Add a curve at the bottom",
    },
    {
      path: "M250,350 Q200,400 150,350",
      pointer: [250, 350],
      direction: "left",
      strokeOrder: 4,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_four_curve",
      visualHint: "Complete the curve at the bottom",
    },
  ],
  "6": [
    {
      path: "M250,250 Q200,200 150,250",
      pointer: [250, 250],
      direction: "left",
      strokeOrder: 1,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_one_top",
      visualHint: "Draw a curve at the top",
    },
    {
      path: "M150,250 Q100,300 150,350",
      pointer: [150, 250],
      direction: "down",
      strokeOrder: 2,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_two_left",
      visualHint: "Add a curve going down to the left",
    },
    {
      path: "M150,350 Q200,400 250,350",
      pointer: [150, 350],
      direction: "right",
      strokeOrder: 3,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_three_bottom",
      visualHint: "Add a curve at the bottom",
    },
    {
      path: "M250,350 Q200,300 150,350",
      pointer: [250, 350],
      direction: "left",
      strokeOrder: 4,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_four_close",
      visualHint: "Close the circle by going back up",
    },
  ],
  "7": [
    {
      path: "M150,200 H250",
      pointer: [150, 200],
      direction: "right",
      strokeOrder: 1,
      strokeType: "crossbar",
      difficulty: "easy",
      audioHint: "stroke_one_across",
      visualHint: "Draw a line across the top",
    },
    {
      path: "M250,200 L150,400",
      pointer: [250, 200],
      direction: "left",
      strokeOrder: 2,
      strokeType: "diagonal",
      difficulty: "medium",
      audioHint: "stroke_two_down",
      visualHint: "Add a line going down to the left",
    },
  ],
  "8": [
    {
      path: "M200,300 Q250,250 200,200",
      pointer: [200, 300],
      direction: "up",
      strokeOrder: 1,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_one_top",
      visualHint: "Draw the top circle",
    },
    {
      path: "M200,200 Q150,250 200,300",
      pointer: [200, 200],
      direction: "down",
      strokeOrder: 2,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_two_bottom",
      visualHint: "Draw the bottom circle",
    },
  ],
  "9": [
    {
      path: "M250,350 Q200,400 150,350",
      pointer: [250, 350],
      direction: "left",
      strokeOrder: 1,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_one_bottom",
      visualHint: "Draw a curve at the bottom",
    },
    {
      path: "M150,350 Q100,300 150,250",
      pointer: [150, 350],
      direction: "up",
      strokeOrder: 2,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_two_left",
      visualHint: "Add a curve going up to the left",
    },
    {
      path: "M150,250 Q200,200 250,250",
      pointer: [150, 250],
      direction: "right",
      strokeOrder: 3,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_three_top",
      visualHint: "Add a curve at the top",
    },
    {
      path: "M250,250 Q300,300 250,350",
      pointer: [250, 250],
      direction: "down",
      strokeOrder: 4,
      strokeType: "curve",
      difficulty: "medium",
      audioHint: "stroke_four_right",
      visualHint: "Close the circle by going down to the right",
    },
  ],
};
