import { lessonTemplates } from "./lessonTypes";

export enum LessonKey {
  // Numbers Island Lessons - Only working ones
  NumberTracing1 = "number_tracing_1",
  NumberTracing2 = "number_tracing_2",
  NumberTracing3 = "number_tracing_3",
  NumberTracing4 = "number_tracing_4",
  NumberTracing5 = "number_tracing_5",
  NumberTracing6 = "number_tracing_6",
  NumberTracing7 = "number_tracing_7",
  NumberTracing8 = "number_tracing_8",
  NumberTracing9 = "number_tracing_9",
  NumberTracing10 = "number_tracing_10",
  CountingFish3 = "counting_fish_3",
  CountingFish5 = "counting_fish_5",
  CountingFish7 = "counting_fish_7",

  // Additional lesson keys referenced in lessonSummary.ts
  NumberMatching = "number_matching",
  NumberQuiz = "number_quiz",
  LetterTracingAEn = "letter_tracing_a_en",
  LetterTracingBEn = "letter_tracing_b_en",
  LetterTracingCEn = "letter_tracing_c_en",
  LetterTracingDEn = "letter_tracing_d_en",
  LetterTracingEEn = "letter_tracing_e_en",
  LetterTracingFEn = "letter_tracing_f_en",
  LetterTracingGEn = "letter_tracing_g_en",
  LetterTracingHEn = "letter_tracing_h_en",
  LetterTracingIEn = "letter_tracing_i_en",
  LetterTracingJEn = "letter_tracing_j_en",
  WordMatchingABC = "word_matching_abc",
  WordMatchingDEF = "word_matching_def",
  WordMatchingGHI = "word_matching_ghi",
  AlphabetQuizABCDE = "alphabet_quiz_abcde",
  AlphabetQuizFGHIJ = "alphabet_quiz_fghij",
  ListeningABCDE = "listening_abcde",
  BasicShapes = "basic_shapes",
  BasicColors = "basic_colors",
  BasicAnimals = "basic_animals",
  BasicFood = "basic_food",
  BasicBodyParts = "basic_body_parts",
  BasicMatching = "basic_matching",
  BasicQuiz = "basic_quiz",
  ColorRed = "color_red",
  ColorBlue = "color_blue",
  ColorGreen = "color_green",
  ColorYellow = "color_yellow",
  ColorPurple = "color_purple",
  ColorOrange = "color_orange",
  ColorMatching = "color_matching",
  ColorQuiz = "color_quiz",
  ShapeCircle = "shape_circle",
  ShapeSquare = "shape_square",
  ShapeTriangle = "shape_triangle",
  ShapeRectangle = "shape_rectangle",
  ShapeStar = "shape_star",
  ShapeHeart = "shape_heart",
  ShapeMatching = "shape_matching",
  ShapeQuiz = "shape_quiz",
  FamilyMembers = "family_members",
  FamilyRelations = "family_relations",
  FamilyActivities = "family_activities",
  FamilyMatching = "family_matching",
  FamilyQuiz = "family_quiz",
  FoodFruits = "food_fruits",
  FoodVegetables = "food_vegetables",
  FoodMeals = "food_meals",
  FoodMatching = "food_matching",
  FoodQuiz = "food_quiz",
  // Conversation Island
  ConversationGreetings = "conversation_greetings",
  ConversationQuestions = "conversation_questions",
  ConversationEmotions = "conversation_emotions",
  ConversationDaily = "conversation_daily",
  ConversationMatching = "conversation_matching",
  ConversationQuiz = "conversation_quiz",
  Greetings = "greetings",
  Feelings = "feelings",
  Weather = "weather",
  DailyRoutine = "daily_routine",
}

export const lessons: Record<
  LessonKey,
  ReturnType<(typeof lessonTemplates)[keyof typeof lessonTemplates]>
> = {
  // Numbers Island Lessons - Only working ones
  [LessonKey.NumberTracing1]: lessonTemplates.numberTracing("1"),
  [LessonKey.NumberTracing2]: lessonTemplates.numberTracing("2"),
  [LessonKey.NumberTracing3]: lessonTemplates.numberTracing("3"),
  [LessonKey.NumberTracing4]: lessonTemplates.numberTracing("4"),
  [LessonKey.NumberTracing5]: lessonTemplates.numberTracing("5"),
  [LessonKey.NumberTracing6]: lessonTemplates.numberTracing("6"),
  [LessonKey.NumberTracing7]: lessonTemplates.numberTracing("7"),
  [LessonKey.NumberTracing8]: lessonTemplates.numberTracing("8"),
  [LessonKey.NumberTracing9]: lessonTemplates.numberTracing("9"),
  [LessonKey.NumberTracing10]: lessonTemplates.numberTracing("10"),
  [LessonKey.CountingFish3]: lessonTemplates.countingFish(3),
  [LessonKey.CountingFish5]: lessonTemplates.countingFish(5),
  [LessonKey.CountingFish7]: lessonTemplates.countingFish(7),

  // Placeholder lessons for lessonSummary.ts compatibility - using unique IDs
  [LessonKey.NumberMatching]: lessonTemplates.numberTracing("matching"),
  [LessonKey.NumberQuiz]: lessonTemplates.numberTracing("quiz"),
  [LessonKey.LetterTracingAEn]: lessonTemplates.letterTracing("A", "en"),
  [LessonKey.LetterTracingBEn]: lessonTemplates.letterTracing("B", "en"),
  [LessonKey.LetterTracingCEn]: lessonTemplates.letterTracing("C", "en"),
  [LessonKey.LetterTracingDEn]: lessonTemplates.letterTracing("D", "en"),
  [LessonKey.LetterTracingEEn]: lessonTemplates.letterTracing("E", "en"),
  [LessonKey.LetterTracingFEn]: lessonTemplates.letterTracing("F", "en"),
  [LessonKey.LetterTracingGEn]: lessonTemplates.letterTracing("G", "en"),
  [LessonKey.LetterTracingHEn]: lessonTemplates.letterTracing("H", "en"),
  [LessonKey.LetterTracingIEn]: lessonTemplates.letterTracing("I", "en"),
  [LessonKey.LetterTracingJEn]: lessonTemplates.letterTracing("J", "en"),
  [LessonKey.WordMatchingABC]: lessonTemplates.numberTracing("abc_match"),
  [LessonKey.WordMatchingDEF]: lessonTemplates.numberTracing("def_match"),
  [LessonKey.WordMatchingGHI]: lessonTemplates.numberTracing("ghi_match"),
  [LessonKey.AlphabetQuizABCDE]: lessonTemplates.numberTracing("abcde_quiz"),
  [LessonKey.AlphabetQuizFGHIJ]: lessonTemplates.numberTracing("fghij_quiz"),
  [LessonKey.ListeningABCDE]: lessonTemplates.numberTracing("abcde_listen"),
  [LessonKey.BasicShapes]: lessonTemplates.numberTracing("basic_shapes"),
  [LessonKey.BasicColors]: lessonTemplates.numberTracing("basic_colors"),
  [LessonKey.BasicAnimals]: lessonTemplates.numberTracing("basic_animals"),
  [LessonKey.BasicFood]: lessonTemplates.numberTracing("basic_food"),
  [LessonKey.BasicBodyParts]: lessonTemplates.numberTracing("basic_body"),
  [LessonKey.BasicMatching]: lessonTemplates.numberTracing("basic_match"),
  [LessonKey.BasicQuiz]: lessonTemplates.numberTracing("basic_quiz"),
  [LessonKey.ColorRed]: lessonTemplates.numberTracing("color_red"),
  [LessonKey.ColorBlue]: lessonTemplates.numberTracing("color_blue"),
  [LessonKey.ColorGreen]: lessonTemplates.numberTracing("color_green"),
  [LessonKey.ColorYellow]: lessonTemplates.numberTracing("color_yellow"),
  [LessonKey.ColorPurple]: lessonTemplates.numberTracing("color_purple"),
  [LessonKey.ColorOrange]: lessonTemplates.numberTracing("color_orange"),
  [LessonKey.ColorMatching]: lessonTemplates.numberTracing("color_match"),
  [LessonKey.ColorQuiz]: lessonTemplates.numberTracing("color_quiz"),
  [LessonKey.ShapeCircle]: lessonTemplates.numberTracing("shape_circle"),
  [LessonKey.ShapeSquare]: lessonTemplates.numberTracing("shape_square"),
  [LessonKey.ShapeTriangle]: lessonTemplates.numberTracing("shape_triangle"),
  [LessonKey.ShapeRectangle]: lessonTemplates.numberTracing("shape_rect"),
  [LessonKey.ShapeStar]: lessonTemplates.numberTracing("shape_star"),
  [LessonKey.ShapeHeart]: lessonTemplates.numberTracing("shape_heart"),
  [LessonKey.ShapeMatching]: lessonTemplates.numberTracing("shape_match"),
  [LessonKey.ShapeQuiz]: lessonTemplates.numberTracing("shape_quiz"),
  [LessonKey.FamilyMembers]: lessonTemplates.numberTracing("family_members"),
  [LessonKey.FamilyRelations]:
    lessonTemplates.numberTracing("family_relations"),
  [LessonKey.FamilyActivities]:
    lessonTemplates.numberTracing("family_activities"),
  [LessonKey.FamilyMatching]: lessonTemplates.numberTracing("family_match"),
  [LessonKey.FamilyQuiz]: lessonTemplates.numberTracing("family_quiz"),
  [LessonKey.FoodFruits]: lessonTemplates.numberTracing("food_fruits"),
  [LessonKey.FoodVegetables]: lessonTemplates.numberTracing("food_vegetables"),
  [LessonKey.FoodMeals]: lessonTemplates.numberTracing("food_meals"),
  [LessonKey.FoodMatching]: lessonTemplates.numberTracing("food_match"),
  [LessonKey.FoodQuiz]: lessonTemplates.numberTracing("food_quiz"),
  [LessonKey.ConversationGreetings]:
    lessonTemplates.numberTracing("conv_greetings"),
  [LessonKey.ConversationQuestions]:
    lessonTemplates.numberTracing("conv_questions"),
  [LessonKey.ConversationEmotions]:
    lessonTemplates.numberTracing("conv_emotions"),
  [LessonKey.ConversationDaily]: lessonTemplates.numberTracing("conv_daily"),
  [LessonKey.ConversationMatching]: lessonTemplates.numberTracing("conv_match"),
  [LessonKey.ConversationQuiz]: lessonTemplates.numberTracing("conv_quiz"),
  [LessonKey.Greetings]: lessonTemplates.numberTracing("greetings"),
  [LessonKey.Feelings]: lessonTemplates.numberTracing("feelings"),
  [LessonKey.Weather]: lessonTemplates.numberTracing("weather"),
  [LessonKey.DailyRoutine]: lessonTemplates.numberTracing("daily_routine"),
};
